language: node_js
node_js:
- 11.9.0
deploy:
  provider: heroku
  api_key:
    secure: L73PdzpXp7ogemhvWBja2H4xplgNkcp/YA0/tIAiv7chrwhoB7BBKPpunz4qPbtiV8tzlD9zi3Hu6S32JS+BabK+EZjEEEuNbCpEnkO9RxssTibdC1KAPr87F9vaRrzXNRqeO3NdaRl4pvtQjFR1UzJyHsMylNlcgv9V/TOmIhMGlRoC14tXLvPuzA8y9j+aoWIUPwpPQqFGZq4sXJ3JYpUQvwd9bRl9Of5YDyskruMZtuxDotEARS2+N1sPHKml9l2eQ0ocTspM0YtwfKngh8dJI8NgGsLnddmfIBV+3/v8DDB/X9+Jbb43khsFxWSgPckcFkPi8NK72nC+X6qWRoyVfJfSDc5Peg3zGGMs8zjOescBfvfbu0+FVRdnMI8NVS1mxTSx4e6msUo+uzproeOBnHkzpm2HiGg4pzLrNNygS5NM2Bd+92b8ufdIjC+haaaW6Xp1G9NhbH4y+hwvVsgr8Qb9k3DzK6zSEZbVDogpUVxToO3ejDepFp1pMA9IGL/9diPxYjZVFCpPti5gNq9YO5RFqmTKTBqUsFAJ+ux3jNF1eT+fgw2RHeL5Eep+UmGQ6Dkwi84FeVne2Rd3PwvHI5ojL/d5EHADt9hSBJt3EwrfQcW1MrMi473QA+B7vmPHKxYCN39X1qXXCyrnVmLX6QGrluWn3R6pg4ljVgw=
  app: books-api-sandbox
  on:
    repo: fullstackmommy/book-api
